apiVersion: v1
kind: ServiceAccount
metadata:
    name: beacondtshadow
---
apiVersion: v1
kind: Service
metadata:
  name: beacondtshadow
  labels:
    app: beacondtshadow
spec:
  ports:
  - port: 9987
    targetPort: 9998   
    name: http
  selector:
    app: beacondtshadow
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: beacondtshadow-v4
  labels:
    version: v4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beacondtshadow
  template:
    metadata:
      labels:
        app: beacondtshadow
        version: v4
      annotations:
        consul.hashicorp.com/connect-inject: 'true'
    spec:
      containers:
      - name: beacondtshadow
        image: timfa/a1pe:beacon
        env:
        - name: FOSTER_SERVICE
          value: /tgcs/1.0.0
        resources:
          requests:
            cpu: 100m
        imagePullPolicy: Always
        ports:
        - containerPort: 9998
      imagePullSecrets:
        - name: foster
