apiVersion: v1
kind: ServiceAccount
metadata:
    name: beacondt
---
apiVersion: v1
kind: Service
metadata:
  name: beacondt
  labels:
    app: beacondt
spec:
  ports:
  - port: 4050
    name: http
  selector:
    app: beacondt
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: beacondt-v4
  labels:
    version: v4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beacondt
  template:
    metadata:
      labels:
        app: beacondt
        version: v4
      annotations: 
        consul.hashicorp.com/connect-inject: 'true'
        'consul.hashicorp.com/connect-service-upstreams': 'beacondt:9998:dc2'
    spec:
      containers:
      - name: beacondt
        image: fosterACR.azurecr.io/foster:4.0
        env:
        - name: FOSTER_SERVICE
          value: ""
        - name: FOSTER_PORT
          value: "4050"
        - name: FOSTER_CLOUD_GW
          value: "http://localhost:9998"
        - name: FOSTER_APIM
          value: "https://preprodapim.umbrellaiot.com:9443"
        - name: FOSTER_TOKEN
          value: "<APPTOKEN>"
        - name: FOSTER_STORAGE
          value: "false"
        - name: FOSTER_DUPLICATE
          value: "false"
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: Always
        ports:
        - containerPort: 4050
      imagePullSecrets:
        - name: foster
